# ============================================================================
# Portfolio Application Configuration
# ============================================================================
# This file contains all application configuration in YAML format
# YAML is more readable and expressive than properties files

portfolio:
  marketdata:
    # Price update intervals (in milliseconds)
    update-interval-min: 500
    update-interval-max: 2000
    
    # Initial stock prices configuration
    # Add new stocks by adding their ticker and initial price
    initial-prices:
      AAPL: "200.00"
      TELSA: "900.00"
      # Example additional stocks (uncomment to use):
      # GOOGL: "2800.00"
      # MSFT: "400.00"
      # AMZN: "3500.00"
  
  # Event Bus Thread Pool Configuration
  eventbus:
    thread-pool:
      core-pool-size: 2
      max-pool-size: 8
      queue-capacity: 100
      keep-alive-seconds: 60
      thread-name-prefix: "event-bus-"
      wait-for-tasks-to-complete-on-shutdown: true
      await-termination-seconds: 30
      rejection-policy: "CALLER_RUNS"  # Options: CALLER_RUNS, ABORT, DISCARD, DISCARD_OLDEST
  
  # Portfolio Manager Scheduled Thread Pool Configuration
  portfolio-manager:
    scheduler:
      core-pool-size: 2
      thread-name-prefix: "portfolio-scheduler-"
      wait-for-tasks-to-complete-on-shutdown: true
      await-termination-seconds: 10

# ============================================================================
# Spring Framework Configuration
# ============================================================================
spring:
  # Database Configuration
  datasource:
    url: jdbc:h2:mem:portfolio
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  
  # H2 Database Console (for development and debugging)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA/Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none  # We use schema.sql for DDL
    show-sql: false   # Set to true for SQL debugging

